import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        border: "var(--border)",
        input: "var(--input)",
        ring: "var(--ring)",
        background: "var(--background)",
        foreground: "var(--foreground)",
        primary: { DEFAULT: "var(--primary)", foreground: "var(--primary-foreground)" },
        secondary: { DEFAULT: "var(--secondary)", foreground: "var(--secondary-foreground)" },
        destructive: { DEFAULT: "var(--destructive)", foreground: "var(--destructive-foreground)" },
        muted: { DEFAULT: "var(--muted)", foreground: "var(--muted-foreground)" },
        accent: { DEFAULT: "var(--accent)", foreground: "var(--accent-foreground)" },
        popover: { DEFAULT: "var(--popover)", foreground: "var(--popover-foreground)" },
        card: { DEFAULT: "var(--card)", foreground: "var(--card-foreground)" },
        chart: {
          1: "var(--chart-1)",
          2: "var(--chart-2)",
          3: "var(--chart-3)",
          4: "var(--chart-4)",
          5: "var(--chart-5)",
        },
        sidebar: {
          DEFAULT: "var(--sidebar)",
          foreground: "var(--sidebar-foreground)",
          primary: "var(--sidebar-primary)",
          "primary-foreground": "var(--sidebar-primary-foreground)",
          accent: "var(--sidebar-accent)",
          "accent-foreground": "var(--sidebar-accent-foreground)",
          border: "var(--sidebar-border)",
          ring: "var(--sidebar-ring)",
        },
        // Legacy brand aliases — wired to shadcn theme tokens so existing classes pick up the theme
        gold: {
          50: "color-mix(in oklch, var(--primary) 8%, var(--background))",
          100: "color-mix(in oklch, var(--primary) 14%, var(--background))",
          200: "color-mix(in oklch, var(--primary) 28%, var(--background))",
          300: "color-mix(in oklch, var(--primary) 45%, var(--background))",
          400: "color-mix(in oklch, var(--primary) 72%, var(--background))",
          500: "var(--primary)",
          600: "color-mix(in oklch, var(--primary) 88%, var(--foreground))",
          700: "color-mix(in oklch, var(--primary) 76%, var(--foreground))",
          800: "color-mix(in oklch, var(--primary) 62%, var(--foreground))",
          900: "color-mix(in oklch, var(--primary) 48%, var(--foreground))",
        },
        ink: {
          50: "var(--muted)",
          100: "color-mix(in oklch, var(--muted) 88%, var(--border))",
          200: "var(--border)",
          300: "color-mix(in oklch, var(--muted-foreground) 35%, var(--border))",
          400: "color-mix(in oklch, var(--muted-foreground) 65%, var(--border))",
          500: "var(--muted-foreground)",
          600: "color-mix(in oklch, var(--foreground) 72%, var(--muted-foreground))",
          700: "color-mix(in oklch, var(--foreground) 82%, var(--muted-foreground))",
          800: "color-mix(in oklch, var(--foreground) 92%, var(--muted-foreground))",
          900: "var(--foreground)",
          950: "var(--foreground)",
        },
        terracotta: {
          50: "color-mix(in oklch, var(--destructive) 8%, var(--background))",
          100: "color-mix(in oklch, var(--destructive) 14%, var(--background))",
          200: "color-mix(in oklch, var(--destructive) 28%, var(--background))",
          300: "color-mix(in oklch, var(--destructive) 45%, var(--background))",
          400: "color-mix(in oklch, var(--destructive) 72%, var(--background))",
          500: "var(--destructive)",
          600: "color-mix(in oklch, var(--destructive) 88%, var(--foreground))",
          700: "color-mix(in oklch, var(--destructive) 76%, var(--foreground))",
          800: "color-mix(in oklch, var(--destructive) 62%, var(--foreground))",
          900: "color-mix(in oklch, var(--destructive) 48%, var(--foreground))",
        },
        cream: "var(--background)",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      fontFamily: {
        sans: ['var(--font-noto-serif)', 'Georgia', 'serif'],
        serif: ['var(--font-noto-serif)', 'Georgia', 'serif'],
      },
      fontSize: {
        display: ['clamp(2.75rem, 5vw, 4.5rem)', { lineHeight: '1.08', letterSpacing: '-0.025em', fontWeight: '400' }],
        h1: ['clamp(2.25rem, 4vw, 3.5rem)', { lineHeight: '1.12', letterSpacing: '-0.02em', fontWeight: '400' }],
        h2: ['clamp(1.625rem, 3vw, 2.25rem)', { lineHeight: '1.2', letterSpacing: '-0.015em', fontWeight: '500' }],
        h3: ['clamp(1.25rem, 2vw, 1.5rem)', { lineHeight: '1.3', letterSpacing: '-0.01em', fontWeight: '500' }],
        h4: ['1.125rem', { lineHeight: '1.35', letterSpacing: '-0.005em', fontWeight: '600' }],
        lead: ['1.1875rem', { lineHeight: '1.75', letterSpacing: '0.012em' }],
        'lead-sm': ['1rem', { lineHeight: '1.65', letterSpacing: '0.01em' }],
        body: ['1.0625rem', { lineHeight: '1.7', letterSpacing: '0.01em' }],
        small: ['0.875rem', { lineHeight: '1.55', letterSpacing: '0.01em' }],
        caption: ['0.75rem', { lineHeight: '1.45', letterSpacing: '0.03em' }],
        eyebrow: ['0.6875rem', { lineHeight: '1.2', letterSpacing: '0.14em', fontWeight: '600' }],
        'card-title': ['1.125rem', { lineHeight: '1.35', letterSpacing: '-0.01em', fontWeight: '500' }],
        'section-title': ['clamp(1.75rem, 3vw, 2.125rem)', { lineHeight: '1.18', letterSpacing: '-0.015em', fontWeight: '400' }],
        'detail-title': ['clamp(2rem, 4vw, 3.25rem)', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '400' }],
        'empty-title': ['1.5rem', { lineHeight: '1.3', letterSpacing: '-0.01em', fontWeight: '400' }],
      },
      animation: {
        'fade-in': 'fadeIn 0.5s ease-in-out',
        'slide-up': 'slideUp 0.4s ease-out',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { opacity: '0', transform: 'translateY(12px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
      },
    },
  },
  plugins: [],
};
export default config;
